name: Node.js
on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Validate and extract release information
        id: release
        uses: manovotny/github-releases-for-automated-package-publishing-action@v1.0.0

      - name: Set node version and build
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: Publish version
        run: yarn publish --new-version ${{ steps.release.outputs.version }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_api_token }}
